# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import hand_pb2 as hand__pb2


class HandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushHand = channel.unary_unary(
                '/HandDetect.HandService/PushHand',
                request_serializer=hand__pb2.ProtoHandRequest.SerializeToString,
                response_deserializer=hand__pb2.ProtoHandResponse.FromString,
                )
        self.DoGreat = channel.unary_unary(
                '/HandDetect.HandService/DoGreat',
                request_serializer=hand__pb2.point3.SerializeToString,
                response_deserializer=hand__pb2.point3.FromString,
                )


class HandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushHand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoGreat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushHand': grpc.unary_unary_rpc_method_handler(
                    servicer.PushHand,
                    request_deserializer=hand__pb2.ProtoHandRequest.FromString,
                    response_serializer=hand__pb2.ProtoHandResponse.SerializeToString,
            ),
            'DoGreat': grpc.unary_unary_rpc_method_handler(
                    servicer.DoGreat,
                    request_deserializer=hand__pb2.point3.FromString,
                    response_serializer=hand__pb2.point3.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HandDetect.HandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushHand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HandDetect.HandService/PushHand',
            hand__pb2.ProtoHandRequest.SerializeToString,
            hand__pb2.ProtoHandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoGreat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HandDetect.HandService/DoGreat',
            hand__pb2.point3.SerializeToString,
            hand__pb2.point3.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
